title: Metal Surface Defect Detection
description: Classical Computer Vision Framework for Industrial Surface Inspection
theme: jekyll-theme-cayman

header_pages:
  - index.md
  - architecture.md
  - methodology.md
  - results.md
