title: Metal Surface Defect Detection
description: Classical Computer Vision Framework for Industrial Surface Inspection
theme: 

header_pages:
  - index.html
  - architecture.html
  - methodology.html
  - results.html

author: Agampreet Singh
